In [1]:
import pandas as pd
df = pd.read_csv('../data/tima_cleaned_data_v1.csv')
df

,STT,application_date,TS_CREDIT_SCORE_V2,Số điện thoại khách hàng,FromDate,ID,LoanID,Số tiền đăng ký vay ban đầu,Tiền giải ngân,Tiền gốc còn lại,...,InterestPaymentType,LongestOverdue,CreditInfo,Name,Address,CheckTime,Brieft,NumberOfLoans,HasBadDebt,HasLatePayment
0,2,NaN,403,977966899,2016-06-24,40,16104,10000000.0,10000000.0,10000000.0,...,Lãi ngày,4,Unknown,Unknown,Unknown,2019-03-17 11:22:15,notfound,0,0,0
1,3,2016-07-28,403,977966899,2016-07-28,226,20871,10000000.0,10000000.0,0.0,...,Lãi ngày,147,Unknown,Unknown,Unknown,2019-03-17 11:22:15,notfound,0,0,0
2,4,2016-06-29,531,397511119,2016-06-29,45,17049,5000000.0,5000000.0,5000000.0,...,Lãi ngày,3,"Khách hàng hiện không có quan hệ tại TCTD, khô...",DAO CONG QUYET,"P203-E9 PHUONG MAI,DONG DA,HA NOI",2019-03-17 08:29:24,0,0,0,0
3,5,2016-06-29,588,abc1234567,2016-06-29,48,17067,10000000.0,10000000.0,10000000.0,...,Lãi ngày,16,"Khách hàng hiện không có quan hệ tại TCTD, khô...",NGUYEN ANH VU,SO 21 NGACH 77/4 LE HONG PHONG-DIEN BIEN-BA DI...,2019-03-17 08:28:09,0,0,0,0
4,6,2016-08-05,675,966710180,2016-08-05,293,22390,10000000.0,10000000.0,0.0,...,Lãi ngày,8,"Khách hàng hiện không có quan hệ tại TCTD, khô...",ĐÀO NGỌC LINH,"-, TT CỤC KHÍ TƯỢNG THỦY VĂN, TRUNG LIỆT, Q.ĐỐ...",2019-03-17 14:14:22,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2378,3181,2018-12-24,577,353833091,2018-12-24,327685,56967,5000000.0,5000000.0,1814424.0,...,Dư nợ giảm dần cố định ngày đóng lãi,0,"Khách hàng hiện đang quan hệ tại 2 TCTD, không...",NGUYỄN HOÀI DUY,"40/8B,,TRẦN XUÂN SOẠN,TÂN THUẬN TÂY,QUẬN 7,TP ...",2019-03-17 11:57:59,2,2,0,0
2379,3182,2018-12-22,638,967295514,2018-12-22,329444,56835,3000000.0,3000000.0,3000000.0,...,Tất toán cuối kỳ,2,"Khách hàng hiện đang quan hệ tại 2 TCTD, không...",TRẦN HÙNG MẠNH,".,.,TỔ 32,PHƯỜNG NGUYỄN PHÚC,YÊN BÁI,TỈNH YÊN BÁI",2019-03-17 11:52:36,2,2,0,0
2380,3184,2018-12-27,605,385669091,2018-12-27,333862,57212,6000000.0,6000000.0,6000000.0,...,Tất toán cuối kỳ,0,"Khách hàng hiện đang quan hệ tại 1 TCTD, không...",LUU VAN HANG,"THANH NGHI, THANH XUAN, HA NOI",2019-03-17 11:43:43,1,1,0,0
2381,3187,2019-01-10,597,869625266,2019-01-10,348341,57938,7000000.0,6000000.0,6000000.0,...,Dư nợ giảm dần cố định ngày đóng lãi,0,"Khách hàng hiện đang quan hệ tại 2 TCTD, không...",NGUYỄN VĂN TRỌNG,THÔN LUẬT NGOẠI 2 - XÃ QUANG LỊCH,2019-03-17 10:47:41,2,2,0,0
2382,3188,2019-01-13,548,383429652,2019-01-13,351190,58148,10000000.0,10000000.0,10000000.0,...,Tất toán cuối kỳ,-3,Unknown,Unknown,Unknown,2019-03-17 09:27:41,notfound,0,0,0

##**Làm sạch dữ liệu**

**Các phần xử lý dữ liệu đã được trình bày ở code task 2**

In [2]:
#missing value
missing = df.isnull().sum().sort_values(ascending=False)
missing_ratio = (missing / len(df) * 100)
missing_df = pd.DataFrame({'MissingCount': missing, 'Missing%': missing_ratio})
missing_df

                             MissingCount  Missing%
CheckTime                             147  6.168695
Birthday                                5  0.209820
Gender                                  4  0.167856
application_date                        1  0.041964
FullNameFamily                          0  0.000000
NameCompany                             0  0.000000
AddressCompany                          0  0.000000
CityCompany                             0  0.000000
DistrictNameCompany                     0  0.000000
Salary                                  0  0.000000
DescriptionPositionJob                  0  0.000000
RelativeFamilyName                      0  0.000000
STT                                     0  0.000000
JobName                                 0  0.000000
InterestPaymentType                     0  0.000000
LongestOverdue                          0  0.000000
CreditInfo                              0  0.000000
Name                                    0  0.000000
Address                                 0  0.000000
Brieft                                  0  0.000000
NumberOfLoans                           0  0.000000
HasBadDebt                              0  0.000000
ProductCreditName                       0  0.000000
DistrictNameHouseHold                   0  0.000000
WardNameHouseHold                       0  0.000000
CityNameHouseHold                       0  0.000000
TS_CREDIT_SCORE_V2                      0  0.000000
Số điện thoại khách hàng                0  0.000000
FromDate                                0  0.000000
ID                                      0  0.000000
LoanID                                  0  0.000000
Số tiền đăng ký vay ban đầu             0  0.000000
Tiền giải ngân                          0  0.000000
Tiền gốc còn lại                        0  0.000000
ToDate                                  0  0.000000
Trạng thái                              0  0.000000
FullName                                0  0.000000
CardNumber                              0  0.000000
CityName                                0  0.000000
DistrictName                            0  0.000000
Hình thức cư trú                        0  0.000000
Thời gian đã sống                       0  0.000000
Street                                  0  0.000000
HasLatePayment                          0  0.000000

##**Tạo đặc trưng (Feature Engineering)**

In [3]:
import pandas as pd
import numpy as np

#Tạo cột Age
df["Birthday"] = pd.to_datetime(df["Birthday"])
df["application_date"] = pd.to_datetime(df["application_date"])

df["Age"] = df["application_date"].dt.year - df["Birthday"].dt.year

df[['application_date', 'Birthday', 'Age']]

     application_date   Birthday   Age
0                 NaT 1987-12-16   NaN
1          2016-07-28 1987-12-16  29.0
2          2016-06-29        NaT   NaN
3          2016-06-29 1989-10-04  27.0
4          2016-08-05 1982-01-31  34.0
...               ...        ...   ...
2378       2018-12-24 1996-12-09  22.0
2379       2018-12-22        NaT   NaN
2380       2018-12-27 1991-11-09  27.0
2381       2019-01-10 1985-12-02  34.0
2382       2019-01-13 1994-10-25  25.0

[2383 rows x 3 columns]

In [4]:
#Tạo AgeGroup
df["AgeGroup"] = pd.cut(
    df["Age"],
    bins=[0, 18, 25, 35, 45, 55, 65, np.inf],
    labels=["<18", "18-25", "26-35", "36-45", "46-55", "56-65", "65+"]
)


df[['Age','AgeGroup']]

       Age AgeGroup
0      NaN      NaN
1     29.0    26-35
2      NaN      NaN
3     27.0    26-35
4     34.0    26-35
...    ...      ...
2378  22.0    18-25
2379   NaN      NaN
2380  27.0    26-35
2381  34.0    26-35
2382  25.0    18-25

[2383 rows x 2 columns]

In [5]:
#Tính LoanTermMonths (kỳ hạn vay theo tháng)
import pandas as pd

df["FromDate"] = pd.to_datetime(df["FromDate"])
df["ToDate"] = pd.to_datetime(df["ToDate"])

df["LoanTermMonths"] = (
    (df["ToDate"].dt.year - df["FromDate"].dt.year) * 12 +
    (df["ToDate"].dt.month - df["FromDate"].dt.month))

df[['FromDate', 'ToDate', 'LoanTermMonths']]

       FromDate     ToDate  LoanTermMonths
0    2016-06-24 2016-07-23               1
1    2016-07-28 2017-03-24               8
2    2016-06-29 2016-12-10               6
3    2016-06-29 2016-10-26               4
4    2016-08-05 2016-12-02               4
...         ...        ...             ...
2378 2018-12-24 2019-03-23               3
2379 2018-12-22 2019-02-21               2
2380 2018-12-27 2019-03-26               3
2381 2019-01-10 2019-04-09               3
2382 2019-01-13 2019-04-12               3

[2383 rows x 3 columns]

In [6]:
#Số ngày xử lý hồ sơ
df["ProcessingDays"] = (df["FromDate"] - df["application_date"]).dt.days

df[["application_date", "FromDate", "ProcessingDays"]]

     application_date   FromDate  ProcessingDays
0                 NaT 2016-06-24             NaN
1          2016-07-28 2016-07-28             0.0
2          2016-06-29 2016-06-29             0.0
3          2016-06-29 2016-06-29             0.0
4          2016-08-05 2016-08-05             0.0
...               ...        ...             ...
2378       2018-12-24 2018-12-24             0.0
2379       2018-12-22 2018-12-22             0.0
2380       2018-12-27 2018-12-27             0.0
2381       2019-01-10 2019-01-10             0.0
2382       2019-01-13 2019-01-13             0.0

[2383 rows x 3 columns]

In [7]:
#LoanToIncomeRatio giúp đánh giá khả năng trả nợ dựa trên lương của khách hàng
df["LoanToIncomeRatio"] = (df["Số tiền đăng ký vay ban đầu"] / df["Salary"]).round(2)

df[["Số tiền đăng ký vay ban đầu", "Salary", "LoanToIncomeRatio"]]

      Số tiền đăng ký vay ban đầu      Salary  LoanToIncomeRatio
0                      10000000.0   7700000.0               1.30
1                      10000000.0   7700000.0               1.30
2                       5000000.0  26000000.0               0.19
3                      10000000.0   8000000.0               1.25
4                      10000000.0  12000000.0               0.83
...                           ...         ...                ...
2378                    5000000.0   7500000.0               0.67
2379                    3000000.0   8000000.0               0.38
2380                    6000000.0   8000000.0               0.75
2381                    7000000.0  12000000.0               0.58
2382                   10000000.0  14000000.0               0.71

[2383 rows x 3 columns]

In [8]:
#Thêm cột số tiền còn lại cần giải ngân
df["Cần Giải Ngân"] = df["Số tiền đăng ký vay ban đầu"] - df["Tiền giải ngân"]

df[["Số tiền đăng ký vay ban đầu", "Tiền giải ngân", "Cần Giải Ngân"]]

      Số tiền đăng ký vay ban đầu  Tiền giải ngân  Cần Giải Ngân
0                      10000000.0      10000000.0            0.0
1                      10000000.0      10000000.0            0.0
2                       5000000.0       5000000.0            0.0
3                      10000000.0      10000000.0            0.0
4                      10000000.0      10000000.0            0.0
...                           ...             ...            ...
2378                    5000000.0       5000000.0            0.0
2379                    3000000.0       3000000.0            0.0
2380                    6000000.0       6000000.0            0.0
2381                    7000000.0       6000000.0      1000000.0
2382                   10000000.0      10000000.0            0.0

[2383 rows x 3 columns]

In [9]:
#Tỷ lệ đã trả của khoản vay
df["Đã trả/khoản vay đã giải ngân"] = (df["Tiền gốc còn lại"] / df["Tiền giải ngân"]).round(2)

df[["Tiền giải ngân", "Tiền gốc còn lại", "Đã trả/khoản vay đã giải ngân"]]

      Tiền giải ngân  Tiền gốc còn lại  Đã trả/khoản vay đã giải ngân
0         10000000.0        10000000.0                           1.00
1         10000000.0               0.0                           0.00
2          5000000.0         5000000.0                           1.00
3         10000000.0        10000000.0                           1.00
4         10000000.0               0.0                           0.00
...              ...               ...                            ...
2378       5000000.0         1814424.0                           0.36
2379       3000000.0         3000000.0                           1.00
2380       6000000.0         6000000.0                           1.00
2381       6000000.0         6000000.0                           1.00
2382      10000000.0        10000000.0                           1.00

[2383 rows x 3 columns]

In [10]:
#Điểm tín dụng thấp
df["LowCreditScore"] = (df["TS_CREDIT_SCORE_V2"] < 600).astype(int)
df[["TS_CREDIT_SCORE_V2", "LowCreditScore"]]

      TS_CREDIT_SCORE_V2  LowCreditScore
0                    403               1
1                    403               1
2                    531               1
3                    588               1
4                    675               0
...                  ...             ...
2378                 577               1
2379                 638               0
2380                 605               0
2381                 597               1
2382                 548               1

[2383 rows x 2 columns]

In [11]:
#CreditScoreGroup
df["CreditScoreGroup"] = pd.cut(
    df["TS_CREDIT_SCORE_V2"],
    bins=[-np.inf, 600, 700, 800, np.inf],
    labels = ["Low (High Risk)", "Medium", "Good", "Excellent"])

df[['TS_CREDIT_SCORE_V2', 'CreditScoreGroup']]

      TS_CREDIT_SCORE_V2 CreditScoreGroup
0                    403  Low (High Risk)
1                    403  Low (High Risk)
2                    531  Low (High Risk)
3                    588  Low (High Risk)
4                    675           Medium
...                  ...              ...
2378                 577  Low (High Risk)
2379                 638           Medium
2380                 605           Medium
2381                 597  Low (High Risk)
2382                 548  Low (High Risk)

[2383 rows x 2 columns]

In [12]:
#IncomeBracket
df["IncomeBracket"] = pd.cut(
    df["Salary"],
    bins=[-np.inf, 5_000_000, 10_000_000, 15_000_000, 25_000_000, np.inf],
    labels=["<5m", "5-10m", "10-15m", "15-25m", ">=25m"]
)

df[['Salary', 'IncomeBracket']]

          Salary IncomeBracket
0      7700000.0         5-10m
1      7700000.0         5-10m
2     26000000.0         >=25m
3      8000000.0         5-10m
4     12000000.0        10-15m
...          ...           ...
2378   7500000.0         5-10m
2379   8000000.0         5-10m
2380   8000000.0         5-10m
2381  12000000.0        10-15m
2382  14000000.0        10-15m

[2383 rows x 2 columns]

In [13]:
#Trang thái khoản vay
import numpy as np

def classify_loan(row):
    if row["Trạng thái"] == "Nợ Xấu":
        return "Nợ xấu"

    elif row["Trạng thái"] == "Đang Vay" and row["LongestOverdue"] >= 1:
        return "Muộn"

    elif row["Trạng thái"] == "Kết thúc":
        return "Hoàn thành"

    else:
        return "Đang vay"

df["LoanStatus"] = df.apply(classify_loan, axis=1)
df[['Trạng thái','LongestOverdue', 'LoanStatus']]

         Trạng thái  LongestOverdue  LoanStatus
0     Đang vay xong               4    Đang vay
1          Kết thúc             147  Hoàn thành
2          Kết thúc               3  Hoàn thành
3          Kết thúc              16  Hoàn thành
4          Kết thúc               8  Hoàn thành
...             ...             ...         ...
2378       Đang Vay               0    Đang vay
2379       Kết thúc               2  Hoàn thành
2380       Kết thúc               0  Hoàn thành
2381       Kết thúc               0  Hoàn thành
2382       Đang Vay              -3    Đang vay

[2383 rows x 3 columns]

In [14]:
df['LoanStatus'].value_counts()

LoanStatus
Hoàn thành    1586
Muộn           525
Nợ xấu         206
Đang vay        66
Name: count, dtype: int64

In [15]:
#Xem lại dữ liệu
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2383 entries, 0 to 2382
Data columns (total 55 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   STT                            2383 non-null   object
 1   application_date               2382 non-null   datetime64[ns]
 2   TS_CREDIT_SCORE_V2             2383 non-null   int64
 3   Số điện thoại khách hàng       2383 non-null   object
 4   FromDate                       2383 non-null   datetime64[ns]
 5   ID                             2383 non-null   int64
 6   LoanID                         2383 non-null   int64
 7   Số tiền đăng ký vay ban đầu    2383 non-null   float64
 8   Tiền giải ngân                 2383 non-null   float64
 9   Tiền gốc còn lại               2383 non-null   float64
 10  ToDate                         2383 non-null   datetime64[ns]
 11  Trạng thái                     2383 non-null   object
 12  FullName                       2383 non-null   object
 13  CardNumber                     2383 non-null   int64
 14  Gender                         2379 non-null   float64
 15  Birthday                       2378 non-null   datetime64[ns]
 16  CityName                       2383 non-null   object
 17  DistrictName                   2383 non-null   object
 18  Hình thức cư trú               2383 non-null   object
 19  Thời gian đã sống              2383 non-null   object
 20  Street                         2383 non-null   object
 21  CityNameHouseHold              2383 non-null   object
 22  DistrictNameHouseHold          2383 non-null   object
 23  WardNameHouseHold              2383 non-null   object
 24  JobName                        2383 non-null   object
 25  NameCompany                    2383 non-null   object
 26  AddressCompany                 2383 non-null   object
 27  CityCompany                    2383 non-null   object
 28  DistrictNameCompany            2383 non-null   object
 29  Salary                         2383 non-null   float64
 30  DescriptionPositionJob         2383 non-null   object
 31  RelativeFamilyName             2383 non-null   object
 32  FullNameFamily                 2383 non-null   object
 33  ProductCreditName              2383 non-null   object
 34  InterestPaymentType            2383 non-null   object
 35  LongestOverdue                 2383 non-null   int64
 36  CreditInfo                     2383 non-null   object
 37  Name                           2383 non-null   object
 38  Address                        2383 non-null   object
 39  CheckTime                      2236 non-null   object
 40  Brieft                         2383 non-null   object
 41  NumberOfLoans                  2383 non-null   int64
 42  HasBadDebt                     2383 non-null   int64
 43  HasLatePayment                 2383 non-null   int64
 44  Age                            2377 non-null   float64
 45  AgeGroup                       2376 non-null   category
 46  LoanTermMonths                 2383 non-null   int32
 47  ProcessingDays                 2382 non-null   float64
 48  LoanToIncomeRatio              2383 non-null   float64
 49  Cần Giải Ngân                  2383 non-null   float64
 50  Đã trả/khoản vay đã giải ngân  2383 non-null   float64
 51  LowCreditScore                 2383 non-null   int64
 52  CreditScoreGroup               2383 non-null   category
 53  IncomeBracket                  2383 non-null   category
 54  LoanStatus                     2383 non-null   object
dtypes: category(3), datetime64[ns](4), float64(10), int32(1), int64(9), object(28)
memory usage: 966.6+ KB

In [16]:
df.isnull().sum()

STT                                0
application_date                   1
TS_CREDIT_SCORE_V2                 0
Số điện thoại khách hàng           0
FromDate                           0
ID                                 0
LoanID                             0
Số tiền đăng ký vay ban đầu        0
Tiền giải ngân                     0
Tiền gốc còn lại                   0
ToDate                             0
Trạng thái                         0
FullName                           0
CardNumber                         0
Gender                             4
Birthday                           5
CityName                           0
DistrictName                       0
Hình thức cư trú                   0
Thời gian đã sống                  0
Street                             0
CityNameHouseHold                  0
DistrictNameHouseHold              0
WardNameHouseHold                  0
JobName                            0
NameCompany                        0
AddressCompany                     0
CityCompany                        0
DistrictNameCompany                0
Salary                             0
DescriptionPositionJob             0
RelativeFamilyName                 0
FullNameFamily                     0
ProductCreditName                  0
InterestPaymentType                0
LongestOverdue                     0
CreditInfo                         0
Name                               0
Address                            0
CheckTime                        147
Brieft                             0
NumberOfLoans                      0
HasBadDebt                         0
HasLatePayment                     0
Age                                6
AgeGroup                           7
LoanTermMonths                     0
ProcessingDays                     1
LoanToIncomeRatio                  0
Cần Giải Ngân                      0
Đã trả/khoản vay đã giải ngân      0
LowCreditScore                     0
CreditScoreGroup                   0
IncomeBracket                      0
LoanStatus                         0
dtype: int64

In [17]:

df.to_csv("../data/tima_cleaned_data_v1.csv", index=False, encoding="utf-8-sig")